### PR TITLE
Only install crush rule when not existing

### PR DESCRIPTION
**Pull request by bjoernt**
Make the playbook idempotent again through adding the CePH crush rule only once during 1st install

### CODE REVIEW

**Comment by byronmccollum** [comment]
This is no longer needed. The `ceph-common` role has a setting to accommodate single node deployments, by setting `common_single_host_mode: true`.

**Comment by bjoernt** [comment]
@byronmccollum  This is still needed. common_single_host_mode just set  " osd crush chooseleaf type = 0" which is not enough anymore since the stock crush map still requires host level replication

**Comment by byronmccollum** [comment]
From what I can tell, this configures the default `replicated_ruleset` rule as follows...

```
rule replicated_ruleset {
    ruleset 0
    type replicated
    min_size 1
    max_size 10
    step take default
    step choose firstn 0 type osd
    step emit
}
```

Is that not effectively the same as the new rule we were previously adding, and updating the pools to use? The only difference I see is choose vs. chooseleaf, but chooseleaf at the OSD level wouldn't have a sub-tree, correct?

**Comment by byronmccollum** [comment]
I started investigating this after noticing MaaS checks would fail before updating the crush-map. This also prevented `verify-maas.yml` from successfully completing.

Now, everything seems to be passing MaaS checks...

**Pull request closed without merging**
