### PR TITLE
Adding CEPH integration into the RPC11 via the ceph tag.

### PR DESCRIPTION
**Pull request by bjoernt**
Adding new ceph node with 3 data and 1 journal volume.
Additionally adding new heat parameters
- New HEAT parameter  rpc_heat_git_url
  - For easy cloning from a forked repo
- New ansible playbook tag ceph
- A new server ceph1 is spun up (node id = 6)
  - With 4 volumes attached (3xdata, 1x journal)
  - The mons are running on the infra nodes

### CODE REVIEW

**Comment by byronmccollum** [comment]
Setting aside some time to look at this. Can you rebase?

**Comment by bjoernt** [comment]
Rebased, testing it right now and see if the ceph patch does apply now

**Comment by byronmccollum** [comment]
Overall looks really good...!

I have a few questions, and a few nits I'll get typed up tomorrow. Thanks for your work on this...

**Comment by bjoernt** [comment]
OMG I solved the ceph-mon submodule patching, what a nightmare with our submodules. I hope we get a high 1st yield build rate now since the ceph_mon key distribution failed every time

**Comment by byronmccollum** [comment]
One more rebase / squash please.

**Comment by bjoernt** [comment]
Rebased... test build running right now.

**Comment by bjoernt** [comment]
@byronmccollum  :+1: 

```
+--------------------------------------+-------------------+-----------------+---------------------+--------------+
| id                                   | stack_name        | stack_status    | creation_time       | updated_time |
+--------------------------------------+-------------------+-----------------+---------------------+--------------+
| f8ea3f43-68a8-4f87-97c2-41b3fe82f428 | bjoern-r11-1-test | CREATE_COMPLETE | 2016-01-11T15:45:45 | None         |
+--------------------------------------+-------------------+-----------------+---------------------+--------------+
```

**Comment by byronmccollum** [comment]
Just FYI...my build failed. Investigating, and will try again.

**Comment by byronmccollum** [comment]
`SSH Error: data could not be sent to the remote host. Make sure this host can be reached over ssh`

Manually re-running playbook...and starting a second fresh build.

**Comment by bjoernt** [comment]
Just rebuild my stack which succeeded

**Comment by byronmccollum** [comment]
Same here...!

**Comment by byronmccollum** [comment]
Thanks again!

**Comment by bjoernt** [comment]
Yay :+1:

**Pull request merged**
