### PR TITLE
Prepare for RPC 12.0 - Liberty

### PR DESCRIPTION
**Pull request by byronmccollum**

### CODE REVIEW

**Comment by mattt416** [comment]
Giving this a run now.

**Comment by mattt416** [comment]
Booted a stack using the following:

```
heat stack-create -t 240 -f templates/rpc-full.yml -P "rpc_release=master;rpc_heat_ansible_release=liberty;ansible_tags=compute,block,object" test
```

Stack created fine.  I think installed tempest and ran a scenario test but it failed on a few tests.  Tried again, and it passed fine:

```
{0} setUpClass (tempest.api.volume.admin.test_volumes_backup.VolumesBackupsV1Test) ... SKIPPED: Cinder backup feature disabled
{1} setUpClass (tempest.api.volume.admin.test_volumes_backup.VolumesBackupsV2Test) ... SKIPPED: Cinder backup feature disabled
{2} tempest.api.orchestration.stacks.test_non_empty_stack.StacksTestJSON.test_list_events [0.127101s] ... ok
{2} tempest.api.orchestration.stacks.test_non_empty_stack.StacksTestJSON.test_list_resources [0.187332s] ... ok
{2} tempest.api.orchestration.stacks.test_non_empty_stack.StacksTestJSON.test_resource_metadata [0.435847s] ... ok
{2} tempest.api.orchestration.stacks.test_non_empty_stack.StacksTestJSON.test_show_event [0.138446s] ... ok
{2} tempest.api.orchestration.stacks.test_non_empty_stack.StacksTestJSON.test_show_resource [0.072734s] ... ok
{2} tempest.api.orchestration.stacks.test_non_empty_stack.StacksTestJSON.test_stack_list [0.068305s] ... ok
{2} tempest.api.orchestration.stacks.test_non_empty_stack.StacksTestJSON.test_stack_show [0.162388s] ... ok
{2} tempest.api.orchestration.stacks.test_non_empty_stack.StacksTestJSON.test_suspend_resume_stack [2.634888s] ... ok
{2} tempest.scenario.test_dashboard_basic_ops.TestDashboardBasicOps.test_basic_scenario [6.589555s] ... ok
{1} tempest.scenario.test_server_basic_ops.TestServerBasicOps.test_server_basicops [43.916186s] ... ok
{0} tempest.scenario.test_minimum_basic.TestMinimumBasicScenario.test_minimum_basic_scenario [80.214506s] ... ok

======
Totals
======
Ran: 13 tests in 88.0000 sec.
 - Passed: 11
 - Skipped: 2
 - Expected Fail: 0
 - Unexpected Success: 0
 - Failed: 0
```

**Comment by byronmccollum** [comment]
Did tempest install and run even though you didn't specify the `tempest` tag. Also, the `network_external` tag wasn't specified. Are there any tempest tests that rely on a working external network and floating IPs?

**Comment by mattt416** [comment]
Hi @byronmccollum, I manually installed tempest (os-tempest-install.yml), which actually creates a public network, private network, and router.  I used the correct public subnet to match the IP configured on br-vlan so it all worked out after I reran.  Not entirely sure why it failed the first time around, I believe they were transient errors since a subsequent run passed but I guess it'd be good to spin up another stack and verify.

**Comment by mattt416** [comment]
Tested this again -- tempest scenario tests ran successfully the first time 'round.  @byronmccollum, can you update this PR to include the tempest changes we made in https://github.com/cloud-training/rpc-heat-ansible/commit/068deaf110b8879502ba37bcab6c6123d9ce586b?

**Comment by byronmccollum** [comment]
Added tempest bits...

**Pull request merged**
